### ISSUE TITLE
Uncaught TypeError: page_title_container is null

### ISSUE THREAD

**Issue by particthistle** [Krshivam25/Joomla_Plugins#1]
![image](https://user-images.githubusercontent.com/5515866/115639558-42513580-a358-11eb-9f54-51ed8b7e4f5f.png)

@Krshivam25 just running a test on this while reviewing GSoC application.

https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector

Looking at the code, when the plugin is enabled, I'm expecting it's going to knock out the page title on every admin page and replace it with the string in the parameter for the plugin... the error in the console shows where that's not happening.

I can see it's loading the parameter properly, but it's not triggering the replacement.

Also, look at improving the XML for the plugin. Joomla has a mechanism in the installer that allows you to overwrite extensions on reinstallation. At the moment if you attempt to install the plugin again, it doesn't allow you to as it detects the existing plugin and won't overwrite it.

Ping your glip mentors channel when you've updated the plugin and have it working so we can test it again.

**Comment by particthistle** [comment]
As you pointed out it's 4 not a 3 plugin. Apologies. 🤦🏻‍♂️ 

![image](https://user-images.githubusercontent.com/5515866/115649104-09ba5780-a36a-11eb-8f9a-5d7900f2446c.png)

So it works 💯 

Can you take a look going forward still (for learning purposes now) at the installation file too, as you'll then see what's needed for when you create other extensions to allow it to override existing extensions.

**Comment by Krshivam25** [comment]
Thankyou @particthistle Surely I will do some hand practice "how to override the existing extensions".
